### ISSUE TITLE
Bug when fetching marketplace's inventory

### ISSUE THREAD

**Issue by agusferreira** [decentraland/account#115]
**Expected Behavior**
A user is trying to access his Estates using the marketplace inventory. His 8 estates should show up.

https://etherscan.io/token/0x959e104e1a4db6317fa58f8295f586e1a978c297?a=0x699C14DA61F21b4db4F2809B59e023F2b1a3D0E6#inventory

**Current Behavior**
The list returns empty (he is correctly signed in with the right account).

![image (13).png](https://images.zenhubusercontent.com/5e1c96e7f4dbe23fe0c77d80/bf264b45-6e5f-4ad9-aa1b-299f58b3b6d8)

**Possible Solution**
When trying to access the Estate preview I encountered a bug ->  I see there is a problem when iterating over an object's data. There might be an issue with the information we are fetching from The Graph.

![Screen Shot 2021-05-17 at 11.04.43.png](https://images.zenhubusercontent.com/5e1c96e7f4dbe23fe0c77d80/a8a66f18-c410-45a6-a270-f43fe339c77c)

https://market.decentraland.org/contracts/0x959e104e1a4db6317fa58f8295f586e1a978c297/tokens/752

Opensea links for missing estates:

https://opensea.io/assets/0x959e104e1a4db6317fa58f8295f586e1a978c297/257
https://opensea.io/assets/0x959e104e1a4db6317fa58f8295f586e1a978c297/743
https://opensea.io/assets/0x959e104e1a4db6317fa58f8295f586e1a978c297/748
https://opensea.io/assets/0x959e104e1a4db6317fa58f8295f586e1a978c297/750
https://opensea.io/assets/0x959e104e1a4db6317fa58f8295f586e1a978c297/749
https://opensea.io/assets/0x959e104e1a4db6317fa58f8295f586e1a978c297/751
https://opensea.io/assets/0x959e104e1a4db6317fa58f8295f586e1a978c297/747
https://opensea.io/assets/0x959e104e1a4db6317fa58f8295f586e1a978c297/752

**Comment by nachomazzara** [comment]
The issue is that the estate is empty

![Screen Shot 2021-05-17 at 11.47.21.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/5ee3e6db-c73f-471c-840f-c9708c94c204)

Maybe we should display that the estate is empty

**Comment by cyaiox** [comment]
@nachomazzara Bug fixed at this PR: https://github.com/decentraland/marketplace/pull/495
