### ISSUE TITLE
Add links to transactions

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/account#124]
Add a link to Etherscan for both Polygon and Ethereum in the account tx history

**Comment by nachomazzara** [comment]
We need to add a new field `txHash` with the hash linked to the correct transaction explorer (etherscan or polygon)
![Screen Shot 2021-09-03 at 09.52.28.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/97aba72a-7473-498b-b75a-5510f4d2c8bc)

For the withdrawal process, we can link the `Withdraw initialized` to the polygon tx. 
![Screen Shot 2021-09-03 at 09.49.54.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/c812db55-201f-43bc-a908-353b951f4a06)

And once the full process is completed:
![Screen Shot 2021-09-03 at 09.51.34.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/5c17265d-0c2c-402a-9882-a5e6f69ececf)

We need to show two transactions hashes:
- `Withdraw Initialized` -> Polygon
- `Withdraw Completed` -> Ethereum
