### ISSUE TITLE
Edit the passport 

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/account#127]
Add the possibility of editing the passport as we had on the Avatars dApp (it was lost in the migration)

**Comment by nachomazzara** [comment]
Add a _pencil_ icon to allow the user to edit their profile description

![Screen Shot 2021-06-25 at 15.29.05.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/ffb5260c-8ab6-4105-abf5-39d360aabe44)

We have the same functionality for editing the collection's name in the [builder](https://github.com/decentraland/builder/blob/master/src/icons/edit.svg):
![Screen Shot 2021-06-25 at 15.31.06.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/f8b0850e-8d77-4092-8d17-4b42b4aaa9d5)

[TBD how to POST the profile to the catalyst @nicosantangelo ]
