### ISSUE TITLE
Allow users to recover the withdraw transaction if they clean the cache by mistake

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/account#132]
If the user changes the browser or clean localstorage, he will lose pending withdraw processes

We must add a modal to allow the user to paste the withdraw transaction hash and recover its progress.

```ts
// user info
const user = '0x68FFc53C43C65C8Dd778969320e21B85b10363cE'
const tx = '0x568f1e9af174aecc3896414dcc5c6fe0fd53aa92c74503e9f5783f400ae72063'
const amount = 3
// insert data into app state
const appState = JSON.parse(localStorage.getItem('account'))
appState.mana.data.withdrawals.push({ 
  hash: tx, 
  amount: amount, 
  from: user,
  status: 'pending',
  timestamp: Date.now()
})
appState.transaction.data.push({ 
  chainId: 80001,
  hash: tx, 
  from: user, 
  status: 'confirmed' ,
  timestamp: Date.now()
})
localStorage.setItem('account', JSON.stringify(appState))
location.reload() // refresh page
```

**Comment by fzavalia** [comment]
Also validate that the user does not add a withdraw that already exists to avoid duplicates

**Comment by cazala** [comment]
Proposal:

- Add a `Recover Withdrawal` option under the three dots menu in the Polygon card
- Open a modal with an explanation in the likes of "Withdrawals are a 2-step process. You initialize a withdrawal with a Polygon transaction that burns your Polygon MANA, and after some minutes you are able to unlock your MANA tokens on Ethereum. We store the information from the first transaction on your device, and it's necessary to finish your withdrawal. If for some reason this information is lost (ie. you erase your browser's storage) or if you are finishing your withdrawal from a new device, you can use this screen to recover your withdrawal information by entering the hash of the withdrawal initialization transaction (in Polygon). You can see all your latest transaction on Polygonscan (link to polygonscan.com/address/...)"
- The modal should have an input for the user to paste the tx hash, and confirm button
- Once the user submits the modal:
  - We should check first if the withdrawal is not already present in state, ignore if so
  - We could create a new `RECOVER_WITHDRAWAL` action and a saga to handle it, the saga should fetch the tx using a matic provider to check the tx actually exists, that it was sent by the user, and to retrieve the amount, and if successful it should dispatch a `watchWithdrawalStatusRequest(amount, hash)` and a `fetchTransactionRequest(address, hash, initiateWithdrawalRequest(amount))`, i think this should be enough to kick all the watchers and have all the data needed in the state to finish the withdrawal.

**Comment by fzavalia** [comment]
@cazala Sounds good to me!
