### ISSUE TITLE
Show "Not enough Mana" error message when user has 0 polygon mana and tries to buy

### ISSUE THREAD

**Issue by nicorajco** [decentraland/account#197]

**Comment by nicorajco** [comment]
At the moment, when trying to buy an item and not having enough Polygon Mana (but more than 0), this is the error showned:
![image.png](https://images.zenhubusercontent.com/617ffbccd0621667f37f36b9/d4824dcb-912d-4beb-ae04-202f5bf49924)

But, if the user has 0 Polygon Mana, instead of that error, this is what the user sees now:
![image.png](https://images.zenhubusercontent.com/617ffbccd0621667f37f36b9/a3c885e0-1350-4eb1-ae2c-4aebcec05656)

The second error should not be that. Instead, we should show the first one. It wouldn't matter if the user has 0 polygon mana or 1. If they don't have enough Polygon Mana, the error should be the same.

**Comment by nicorajco** [comment]
Plus: if we could say "Polygon MANA" instead of just "MANA" for items that are in that network, it would be great :) 
If not, we can live with that.

**Comment by nachomazzara** [comment]
Issue moved to [decentraland/marketplace #578](https://github.com/decentraland/marketplace/issues/578) via [**ZenHub**](https://www.zenhub.com/)
